# dependencies
#
# To use:
```bash
conda env create -f environment.yml
conda activate bmc-h_polymorphism
```
#
# To update dependencies after changing this environment file:
#   conda env update --name bmc-h_polymorphism --file environment.yml --prune
#
name: bmc-h_polymorphism
channels:
  - conda-forge
dependencies:
  - numpy=1.23.3
  - matplotlib=3.4.3
  - seaborn=0.12.0

  # include jupyterlab for convenience
  - jupyterlab
